version: '3.4'

services:
  frontendsource:
    image: frontendsource
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    # ports:
    #   - 4200:4200
    volumes:
      - ./:/usr/src/app:cached

